// GENERATED by scripts/prepare-tokenizer.mjs — do not edit by hand.
// Pinned tokenizer data sources (URLs immutable via repo commit; sha256 verified).
// Runtime strategy: fetch at first use (CORS-verified), cache in IndexedDB,
// HeuristicEngine fallback offline/unknown. See docs/m0-spike.md (G1).
export interface TokenizerFamilyFile {
  name: string;
  url: string;
  sha256: string;
}

export interface TokenizerFamily {
  id: string;
  label: string;
  /** RegExp source matched against the session's current model id. */
  match: string;
  note: string;
  files: TokenizerFamilyFile[];
}

export const TOKENIZER_FAMILIES: TokenizerFamily[] = [
  {
    "id": "deepseek",
    "label": "DeepSeek 128k BPE",
    "match": "^deepseek",
    "note": "DeepSeek-V3 tokenizer (byte-level BPE, 128k). License: DeepSeek Model LICENSE (LICENSE-MODEL) + code MIT (LICENSE-CODE).",
    "files": [
      {
        "name": "tokenizer.json",
        "url": "https://huggingface.co/deepseek-ai/DeepSeek-V3/resolve/e815299b0bcbac849fa540c768ef21845365c9eb/tokenizer.json",
        "sha256": "621ac2e32d0dba658404412318818aaa8ce8cda492e59830109d8da6b517fb41"
      },
      {
        "name": "tokenizer_config.json",
        "url": "https://huggingface.co/deepseek-ai/DeepSeek-V3/resolve/e815299b0bcbac849fa540c768ef21845365c9eb/tokenizer_config.json",
        "sha256": "637bcd1a08cf7c772ce6a383196b22930921c79c3c73223c5afc0c7f41545546"
      }
    ]
  },
  {
    "id": "gpt-o200k",
    "label": "OpenAI o200k_base (GPT-4o/5)",
    "match": "^(gpt-4o|gpt-5|o[134]-|o1|o3|o4|chatgpt-)",
    "note": "OpenAI o200k_base via wellflat/o200k_base_tokenizer (transformers format). Data copyright OpenAI (tiktoken, MIT); repo has no explicit license — review before external distribution.",
    "files": [
      {
        "name": "tokenizer.json",
        "url": "https://huggingface.co/wellflat/o200k_base_tokenizer/resolve/6284f55841ce3ae7cc7295b9be7a99a627a88743/tokenizer.json",
        "sha256": "27f8a5a5997a1aa0e6ac889e213b24a99c342831ab59cccc1638b878370c20f0"
      },
      {
        "name": "tokenizer_config.json",
        "url": "https://huggingface.co/wellflat/o200k_base_tokenizer/resolve/6284f55841ce3ae7cc7295b9be7a99a627a88743/tokenizer_config.json",
        "sha256": "f213bebce96d081d0e70ca0dd4548e4a708c544e34d7251db9a9f623a1b2bc2f"
      }
    ]
  },
  {
    "id": "gpt-cl100k",
    "label": "OpenAI cl100k_base (GPT-3.5/4)",
    "match": "^(gpt-4(?!o)|gpt-3\\.5|text-davinci|text-curie)",
    "note": "OpenAI cl100k_base via Xenova/gpt-4 (transformers format). Data copyright OpenAI (tiktoken, MIT); repo carries no license file — review before external distribution.",
    "files": [
      {
        "name": "tokenizer.json",
        "url": "https://huggingface.co/Xenova/gpt-4/resolve/1d9f1f1b1fae88c0e4df1dab0a397f8de6229075/tokenizer.json",
        "sha256": "239eb2359f79c38497476671aaa835e01fb43d42743c612a8514a0dfa2ac93a2"
      },
      {
        "name": "tokenizer_config.json",
        "url": "https://huggingface.co/Xenova/gpt-4/resolve/1d9f1f1b1fae88c0e4df1dab0a397f8de6229075/tokenizer_config.json",
        "sha256": "185a09e9fcc9892ff26caf97e586f16a80a49cf9ec849d10d008890332881428"
      }
    ]
  }
];
